### ISSUE TITLE
Support Light Mode & Dark Mode

### ISSUE THREAD

**Issue by Spikeysanju** [TheCodeMonks/NYTimes-App#11]
### Proposed Change

- Support for Light/Dark mode using **_`Datastore`_**
- This change is to encourage the participants of **_`Hacktoberfest 2020`_** for the this events

### Reference

_**`Datastore`**_ -  https://developer.android.com/topic/libraries/architecture/datastore

**Comment by SourabhSNath** [comment]
Hello, I'd like to try this one

**Comment by Spikeysanju** [comment]
Hey, @SourabhSNath  thanks for your interest. Looking forward to your implementation. All the best 😄👍

**Comment by SourabhSNath** [comment]
Does this project need Android Studio Canary? Because I get an error asking for later versions on Gradle Build

**Comment by Spikeysanju** [comment]
Probably yes, You need to install android studio Canary
