### ISSUE TITLE
Add Theme Engine

### ISSUE THREAD

**Issue by DrewStephensCoding** [TheCodeMonks/NYTimes-App#117]
Great work on the app! One change I was thinking about, was using a theme engine like [Cyanea](https://github.com/jaredrummler/Cyanea) I've used it in a past app of mine and is easy to implement and I think would give NYTimes-App great character

**Comment by Spikeysanju** [comment]
@DrewStephensCoding  Buddy thanks for this feature request. But I think our NYTimes app is kind of minimal application & also Both Day/ Night mode already works well. Any will keep this FR in my mind. Thanks for taking time to raise a Feature Request.
