### ISSUE TITLE
App crashes when open in offline mode

### ISSUE THREAD

**Issue by ch8n** [TheCodeMonks/NYTimes-App#16]
### Steps to reproduce
1. Go offline in the current device
2. Open Application

### Expected behavior 
App open with no internet message

### Actual behavior 
App crashes immediately

**Comment by ch8n** [comment]
@Spikeysanju kindly assign it to me. and also link with previous issue

**Comment by ch8n** [comment]
> @Spikeysanju kindly assign it to me. and also link with previous issue

Hi please mark this as hacktoberfest topic else i will not earn PR. 🙈
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Spikeysanju** [comment]
@ch8n Done mate. You can start your work peacefully 😉

**Comment by ch8n** [comment]
> @ch8n Done mate. You can start your work peacefully 😉

Please do add the previous one with the tag of hacktoberfest accepted tag else that will not come under consideration

**Comment by Spikeysanju** [comment]
@ch8n Updated labels & Added topic 👍
