### ISSUE TITLE
[Suggestion] introduce dependency injection

### ISSUE THREAD

**Issue by ch8n** [TheCodeMonks/NYTimes-App#18]
Hi @Spikeysanju you can introduce DI in this project 
if you don't  want to deal with Dagger, you can do manual DI using only Kotlin,
you can see my approach from below post
https://proandroiddev.com/hold-on-before-you-dagger-or-hilt-try-this-simple-di-f674c83ebeec

**Comment by cfsnsalazar** [comment]
I would use Koin. Much better

**Comment by Spikeysanju** [comment]
@ch8n @cfsnsalazar Thanks for the suggestion. I'm planning to add `Hilt` to this project. Thanks for the contribution 🙌

**Comment by ch8n** [comment]
@Spikeysanju how about doing it on a live stream? 🤩 👨🏻‍💻
