### ISSUE TITLE
share article url

### ISSUE THREAD

**Issue by ELTEGANI** [TheCodeMonks/NYTimes-App#21]
share article URL from article details page using [ShareSheet](https://developer.android.com/training/sharing/send#why-to-use-system-sharesheet)
@Spikeysanju

**Comment by Spikeysanju** [comment]
@ELTEGANI  Sure will add this feature by today itself mate 👍

**Comment by ELTEGANI** [comment]
> @ELTEGANI Sure will add this feature by today itself mate
So no problem with it to make PR @Spikeysanju

**Comment by Spikeysanju** [comment]
@ELTEGANI  Yes mate, Contributions are always welcome. I will assign this to you. You start working on it. 

For `Share Icon` kindly take the icon from this website - [Tabler Icons](https://tablericons.com)

Make sure you make PR to the Dev branch

**Comment by Spikeysanju** [comment]
@ELTEGANI  Task assigned for you 👍
