### ISSUE TITLE
Introduce View Binding instead of Kotlin synthetic binding (deprecated)

### ISSUE THREAD

**Issue by Spikeysanju** [TheCodeMonks/NYTimes-App#36]

**Comment by cfsnsalazar** [comment]
I can help with this if you have not started yet

**Comment by Spikeysanju** [comment]
@cfsnsalazar Thanks for your interest. I have updated the code for all fragments. The only thing pending rn is the Recycler Adapter class. Can you work on it?

**Comment by cfsnsalazar** [comment]
Yup

**Comment by cfsnsalazar** [comment]
Would I still get hacktoberfest credit for this ?

**Comment by Spikeysanju** [comment]
Yes, I think so. But I don't know about the mature period it would get around 10 days to validate this PR.

**Comment by cfsnsalazar** [comment]
That's fine . I was just wondering if I would get the label on my PR, which it has been already answered
