### ISSUE TITLE
Article List Flickering when tabs are changes

### ISSUE THREAD

**Issue by ch8n** [TheCodeMonks/NYTimes-App#86]
# Bug
When ever we switch tabs the list first shows the previous data then flicker to a new list

## Expected
on switch tabs no flickering should appear

**Comment by Spikeysanju** [comment]
@ch8n Good catch buddy!... I will work on this 👍

**Comment by DrewStephensCoding** [comment]
I found that adding articleRv.itemAnimator = null to ArticlesFragment.kt in the below function solves the flickering
```
    private fun observeArticles() = with(binding) {
        // observe the articles
        viewModel.articles.observe(viewLifecycleOwner) {
            refreshArticles.isRefreshing = false
            newsAdapter.differ.submitList(it)
            articleRv.animate().alpha(1f)
            articleRv.itemAnimator = null   //adding this line, stops the flickering
        }
    }
```

**Comment by Spikeysanju** [comment]
@DrewStephensCoding Nice catch buddy!... If possible can you pls create a PR for this?
